#!groovy

//使用共享库
@Library('jenkins-shared-library@main') _

//调用函数


currentBuild.displayName = "${env.branchName}"
currentBuild.description = "xxx"

pipeline {
    agent {
        kubernetes {
            retries 2
            yaml '''               
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: git
                image: registry.cn-hangzhou.aliyuncs.com/tool-bucket/tool:git
                command:
                - cat
                tty: true              
              - name: golang
                image: golang:1.16.5
                command:
                - cat
                tty: true                                
            '''
        }
    }
    options {
        skipDefaultCheckout true
    }

    stages{
    stage("GetCode"){
        steps{
            script{
                checkout scmGit(branches: [[name: "${env.branchName}"]], 
                    extensions: [], userRemoteConfigs: [[credentialsId: 'GitHub_credentials', 
                    url: "${env.srcUrl}"]])
                sh "ls -l "
                }
            }        
        }
    }
}